DROP TABLE Supplier;
CREATE TABLE Supplier (SupID INT PRIMARY KEY, SupName VARCHAR(50), City VARCHAR(50));
INSERT INTO Supplier VALUES (1, 'Alpha', 'Jakarta');
INSERT INTO Supplier VALUES (2, 'Beta', 'Bandung');
INSERT INTO Supplier VALUES (3, 'Gamma', 'Surabaya');
INSERT INTO Supplier VALUES (4, 'Supplier 4', 'Medan');
INSERT INTO Supplier VALUES (5, 'Supplier 5', 'Semarang');
INSERT INTO Supplier VALUES (6, 'Supplier 6', 'Jakarta');
INSERT INTO Supplier VALUES (7, 'Supplier 7', 'Bandung');
INSERT INTO Supplier VALUES (8, 'Supplier 8', 'Surabaya');
INSERT INTO Supplier VALUES (9, 'Supplier 9', 'Medan');
INSERT INTO Supplier VALUES (10, 'Supplier 10', 'Semarang');
INSERT INTO Supplier VALUES (11, 'Supplier 11', 'Jakarta');
INSERT INTO Supplier VALUES (12, 'Supplier 12', 'Bandung');
INSERT INTO Supplier VALUES (13, 'Supplier 13', 'Surabaya');
INSERT INTO Supplier VALUES (14, 'Supplier 14', 'Medan');
INSERT INTO Supplier VALUES (15, 'Supplier 15', 'Semarang');
INSERT INTO Supplier VALUES (16, 'Supplier 16', 'Jakarta');
INSERT INTO Supplier VALUES (17, 'Supplier 17', 'Bandung');
INSERT INTO Supplier VALUES (18, 'Supplier 18', 'Surabaya');
INSERT INTO Supplier VALUES (17, 'Supplier 17', 'B');
INSERT INTO Supplier VALUES (99, 'Supplier 17', 'B');
INSERT INTO Supplier VALUES (100, 'Supplier 17', 'Ban');
INSERT INTO Supplier VALUES (100, 'Supplier 17', 'Band');
INSERT INTO Supplier VALUES (100, 'Supplier 17', 'Bandun');
INSERT INTO Supplier VALUES (100, 'Supplier 17', 'Mandala');
INSERT INTO Supplier VALUES (100, 'Supplier 17', 'BORMA');